# Generated by Django 5.1 on 2024-10-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='purchase_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='provider',
            new_name='source',
        ),
    ]
