# Generated by Django 5.1 on 2024-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kitchen', '0002_rename_purchase_price_ingredient_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='chef_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='chef_permission_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
